version: '3.9'

services:
  db:
    image: mongo:4.4
    restart: always
    container_name: nexus-ai
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: tests